windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAEAAABVUAAAL/AAAAAAAAABAAAAVVAAAC/wAAAAAAAAAABVYAAAAAAAAA
    EAAABVUAAAL/
  tabs:
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Arch Linux - capitaine-cursors 4-1 (any)
      url: https://archlinux.org/packages/community/any/capitaine-cursors/
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: archlinux - Where can I get libGLU.so.1 on Arch Linux? - Stack Overflow
      url: https://stackoverflow.com/questions/66486937/where-can-i-get-libglu-so-1-on-arch-linux
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Doručená pošta (2 244) - xmacto01@gjk.cz - Gymnázium Jana Keplera Mail
      url: https://mail.google.com/mail/u/0/#inbox
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Kurzy
      url: https://classroom.google.com/h
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: OLED displej 0.91" 128x32, I2C, bílý | GM electronic, spol. s.r.o.
      url: https://www.gme.cz/i2c-bily-oled-display-0-91-128x32
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:27'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: OLED displej 0.91" 128x32, I2C, bílý | GM electronic, spol. s.r.o.
      url: https://www.gme.cz/i2c-bily-oled-display-0-91-128x32
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:27'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Usage | Adafruit PiOLED - 128x32 Mini OLED for Raspberry Pi | Adafruit
        Learning System
      url: https://learn.adafruit.com/adafruit-pioled-128x32-mini-oled-for-raspberry-pi/usage
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: How to Use ALSA Utilities to Manage Linux Audio from the Terminal - Make
        Tech Easier
      url: https://www.maketecheasier.com/alsa-utilities-manage-linux-audio-command-line/
      zoom: 0.8
  - history:
    - active: true
      last_visited: '2022-01-07T12:41:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: JACK Audio Connection Kit - ArchWiki
      url: https://wiki.archlinux.org/title/JACK_Audio_Connection_Kit
      zoom: 0.8
  - history:
    - last_visited: '2022-01-07T12:41:29'
      pinned: false
      title: DuckDuckGo — Privacy, simplified.
      url: https://start.duckduckgo.com/
    - last_visited: '2022-01-07T12:41:33'
      pinned: false
      title: ty at DuckDuckGo
      url: https://duckduckgo.com/?q=ty&ia=web
    - last_visited: '2022-01-07T12:41:37'
      pinned: false
      title: yt at DuckDuckGo
      url: https://duckduckgo.com/?q=yt&ia=web
    - last_visited: '2022-01-07T12:41:46'
      pinned: false
      title: YouTube
      url: https://www.youtube.com/
    - active: true
      last_visited: '2022-01-07T12:41:46'
      original-url: https://www.youtube.com/
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Wife PC Upgrade NIGHTMARE - YouTube
      url: https://www.youtube.com/watch?v=QCm9R4yJXhE
      zoom: 0.8
  - active: true
    history:
    - active: true
      last_visited: '2022-01-07T13:56:33'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: start.duckduckgo.com
      url: https://start.duckduckgo.com/
      zoom: 0.8
