#!/bin/sh

ethstatus="$(cat /sys/class/net/eth0/operstate)"

wifistatus="$(cat /sys/class/net/wlan0/operstate)"
wifissid="$(nmcli -t -f NAME connection show --active)"
wifiperc="$(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) "%" }')"

ip="$(ip route get 1.1.1.1 | sed -n '/src/{s/.*src *\([^ ]*\).*/\1/p;q}')"

if [ $ethstatus = "up" ]; then
    netstatus="^c#d77921^ ^d^eth0"
    printf "%s^c#d77921^^d^%s\n" "$netstatus" "$ip"
elif [ $wifistatus = "up" ]; then
    netstatus="^c#d77921^ ^d^$wifiperc"
    printf "%s^c#d77921^^d^%s\n" "$netstatus" "$ip"
else
    netstatus="^c#d77921^"
    printf "%s" "$netstatus"
fi
